import type { Metadata } from 'next'
import { site } from '@/content/site'

/** Generated by `src/app/opengraph-image.tsx`; referenced explicitly because a page-level
 * `openGraph` object replaces the root one and would otherwise drop the file-based image. */
const OG_IMAGE = { url: '/opengraph-image', width: 1200, height: 630, alt: site.name }

/** Metadata applied at the root layout; pages override title/description/canonical. */
export const rootMetadata: Metadata = {
  metadataBase: new URL(site.url),
  title: { default: site.name, template: `%s · ${site.name}` },
  description: site.description,
  alternates: {
    canonical: '/',
    types: { 'application/rss+xml': '/feed.xml' },
  },
  openGraph: {
    type: 'website',
    siteName: site.name,
    locale: 'en_US',
    url: '/',
    title: site.name,
    description: site.description,
    images: [OG_IMAGE],
  },
  twitter: {
    card: 'summary_large_image',
    title: site.name,
    description: site.description,
    images: [OG_IMAGE.url],
  },
  robots: { index: true, follow: true },
}

type PageMetadataInput = {
  /** Omit on the home page so the root default title applies. */
  title?: string
  description: string
  /** Route path starting with "/", used for canonical and Open Graph URLs. */
  path: string
  type?: 'website' | 'article'
  /** ISO date for articles. */
  publishedTime?: string
}

export function pageMetadata({
  title,
  description,
  path,
  type = 'website',
  publishedTime,
}: PageMetadataInput): Metadata {
  const displayTitle = title ?? site.name
  return {
    ...(title !== undefined && { title }),
    description,
    alternates: { canonical: path },
    openGraph:
      type === 'article'
        ? {
            type: 'article',
            url: path,
            title: displayTitle,
            description,
            publishedTime,
            authors: [site.legalName],
            images: [OG_IMAGE],
          }
        : {
            type: 'website',
            url: path,
            title: displayTitle,
            description,
            images: [OG_IMAGE],
          },
    twitter: {
      card: 'summary_large_image',
      title: displayTitle,
      description,
      images: [OG_IMAGE.url],
    },
  }
}
